const fruteria = {
  frutas: {
    manzanas: {
      cantidad: 20,
      precio: 1.5,
      enOferta: false,
      tipo: "Golden",
    },
    bananas: {
      cantidad: 30,
      precio: 0.5,
      enOferta: true,
      tipo: "Cavendish",
    },
    naranjas: {
      cantidad: 15,
      precio: 0.8,
      enOferta: true,
      tipo: "Valencia",
    },
    peras: {
      cantidad: 10,
      precio: 1.2,
      enOferta: false,
      tipo: "Conferencia",
    },
    kiwis: {
      cantidad: 25,
      precio: 0.4,
      enOferta: false,
      tipo: "Hayward",
    },
    mangos: {
      cantidad: 5,
      precio: 2.0,
      enOferta: true,
      tipo: "Tommy Atkins",
    },
    fresas: {
      cantidad: 40,
      precio: 0.3,
      enOferta: false,
      tipo: "Festival",
    },
    arandanos: {
      cantidad: 20,
      precio: 1.0,
      enOferta: false,
      tipo: "Bluecrop",
    },
    limones: {
      cantidad: 12,
      precio: 0.6,
      enOferta: true,
      tipo: "Meyer",
    },
    sandias: {
      cantidad: 2,
      precio: 4.0,
      enOferta: false,
      tipo: "Crimson Sweet",
    },
  },
  verduras: {
    lechuga: {
      cantidad: 10,
      precio: 0.7,
      enOferta: false,
      tipo: "Romana",
      origen: "España",
      frescura: 3,
    },
    zanahorias: {
      cantidad: 25,
      precio: 0.4,
      enOferta: true,
      tipo: "Baby",
      origen: "Francia",
      frescura: 5,
    },
    tomates: {
      cantidad: 18,
      precio: 0.9,
      enOferta: true,
      tipo: "Cherry",
      origen: "Italia",
      frescura: 2,
    },
    cebollas: {
      cantidad: 30,
      precio: 0.3,
      enOferta: false,
      tipo: "Blanca",
      origen: "Holanda",
      frescura: 4,
    },
    pimientos: {
      cantidad: 12,
      precio: 1.2,
      enOferta: false,
      tipo: "Verde",
      origen: "España",
      frescura: 1,
    },
    calabacines: {
      cantidad: 22,
      precio: 0.6,
      enOferta: true,
      tipo: "Italiano",
      origen: "México",
      frescura: 4,
    },
    esparragos: {
      cantidad: 8,
      precio: 2.5,
      enOferta: false,
      tipo: "Verde",
      origen: "Perú",
      frescura: 3,
    },
    brocoli: {
      cantidad: 14,
      precio: 1.0,
      enOferta: false,
      tipo: "Calabrese",
      origen: "Estados Unidos",
      frescura: 5,
    },
    pepinos: {
      cantidad: 20,
      precio: 0.8,
      enOferta: true,
      tipo: "Holandes",
      origen: "España",
      frescura: 3,
    },
    coliflor: {
      cantidad: 12,
      precio: 1.3,
      enOferta: false,
      tipo: "Blanca",
      origen: "Italia",
      frescura: 2,
    },
  },
};
